version: '3.7'

services:
  front-end:
    image: rainier1234/pe-frontend-rainierbastiaans-main2:latest
    restart: always
    ports:
      - "3000:3000"

  back-end:
    image: rainier1234/pe-backend-rainierbastiaans-main:latest
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_NAME: pdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: pdb
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
