version: '3.7'

services:
  front-end:
    image: rainier1234/pe-frontend-rainierbastiaans-main2:latest
    container_name: "frontend"
    restart: unless-stopped
    environment:
       port: 3000
    ports:
      - "3000:3000"

  back-end:
    image: rainier1234/pe-backend-rainierbastiaans-main:latest
    restart: unless-stopped
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_HOST: sqldb
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306